### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by syats** [pan-dora/trellis#3]
Hello maintainers of Trellis Linked Data Platform,

Could you please confirm that the docker image hoster here:
https://hub.docker.com/r/trellisldp/jpms.app.triplestore.5/
Is generated with the Dockerfile here:
https://github.com/trellis-ldp/trellis-deployment/tree/master/trellis-compose/trellis-app-triplestore/1.10
?

Thanks,
Victor

**Comment by acoburn** [comment]
Pinging @christopher-johnson, since he's the one who maintains that docker image, but judging from the `jpms` portion of the docker image name, I suspect that the image is based on a local build of the jpms branch of the main trellis repository, combined with the Dockerfile to which you link.

I would add that the Docker image for the main line of Trellis development is at: https://hub.docker.com/r/trellisldp/trellis/. This docker image is regenerated with every commit to the master branch. The other Docker image that is published with each commit is https://hub.docker.com/r/trellisldp/trellis-ext-db/. More information about the Trellis docker containers is available here: https://github.com/trellis-ldp/trellis/wiki/Dockerized-Trellis

**Comment by christopher-johnson** [comment]
yes.  that docker file created the image on docker hub.  it actually pulls a (very old) release here:
https://github.com/christopher-johnson/trellis/releases/tag/trellis-jpms-0.7.0

as @acoburn indicates, It would probably be better to build from a more recent source and / or use the normal docker images created from master, since trellis-deployment is not actively maintained.

**Comment by syats** [comment]
Thanks both of you for the input!
You are right, it is a better idea to use the newest images that are autobuilt.
However,
   I am trying to deploy on openshift and the images in the dockerhub can't run on it (long story, blame OpenShift). 
  Therefore, I am re-building the images with some tweaks on the Dockerfiles.

Where can I find the Dockerfile that builds the images available here: https://hub.docker.com/r/trellisldp/trellis/ ? 

Thanks!

**Comment by acoburn** [comment]
@syats you can find the Dockerfile in this directory: https://github.com/trellis-ldp/trellis/tree/master/platform/server/src/docker

In addition, there is some configuration defined here: https://github.com/trellis-ldp/trellis/blob/master/platform/server/build.gradle#L65-L86

If there are ways to fix up those Docker images to run better, feel free to send along a PR.

**Comment by syats** [comment]
Thanks a lot! 
I will build from these and let you know if I improve anything!

Keep up the good work!
